-   id: format-package-xml
    name: Format package.xml files
    description: Verify the package xml schema and ordering of dependencies
    entry: package-xml-formatter
    language: python
    files: ^.*package\.xml$