name: Python Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: ros:jazzy-ros-base
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev
          sudo apt-get install -y pip
          sudo apt-get install -y python3-rosdep

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir lxml
          python -m pip install . --break-system-packages

      - name: Update rosdep
        run: |
          rosdep update

      - name: Run unit tests
        env:
          PYTHONUNBUFFERED: 1
        run: |
          python -u -m unittest discover -v
